sudo: required
language: generic

services:
  - docker

env:
  global:
    - CADDYSHACK_VERSION: 1.0.4
    - DOCKER_COMPOSE_VERSION: 1.24.1

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker restart
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - CADDYSHACK_VERSION=$CADDYSHACK_VERSION docker-compose build caddy

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker tag coyotesys/caddy:$CADDYSHACK_VERSION coyotesys/caddy:latest;
      docker push coyotesys/caddy:$CADDYSHACK_VERSION;
      docker push coyotesys/caddy:latest;
    fi
